# Generated by Django 4.1.1 on 2022-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('UserPassword', models.CharField(max_length=20)),
                ('UserEmail', models.CharField(max_length=25)),
            ],
        ),
    ]
